### ISSUE TITLE
Warning: No SupportedSourceVersion annotation found

### ISSUE THREAD

**Issue by badoualy** [sczerwinski/android-hilt#127]
### Steps

Build

### Result

Warning: No SupportedSourceVersion annotation found

### Solution

`HiltModulesGenerator` needs to override `getSupportedSourceVersion`

eg:

```kotlin
    override fun getSupportedSourceVersion(): SourceVersion {
        return SourceVersion.RELEASE_8
    }
```

**Comment by sczerwinski** [comment]
Added annotation instead:
```kotlin
@SupportedSourceVersion(SourceVersion.RELEASE_8)
```

**Comment by sczerwinski** [comment]
It's not a blocking issue. I won't rush with the new release.

**Comment by badoualy** [comment]
Ok for me, I'm using the jitpack artifact anyway, so I can use any commit hash as a version :)
