### ISSUE TITLE
KSP processor

### ISSUE THREAD

**Issue by sczerwinski** [sczerwinski/android-hilt#191]
Implement `hilt-processor` as KSP processor (either in the same library, or as a separate `hilt-processor-ksp` library).

The KSP processor should duplicate the functionality of the existing Kapt processor, but it should be managed by KSP instead.

Ticket for official KSP support for Hilt: https://issuetracker.google.com/issues/179057202

**Comment by sczerwinski** [comment]
This is also an opportunity to properly refactor existing Kapt processor.

**Comment by Kshitij09-sc** [comment]
Any reason you didn't implement it already? What are the current blockers to write a hilt extension using KSP?

**Comment by sczerwinski** [comment]
Thanks for your question, @Kshitij09-sc

The main reason is me working on other projects. KSP simply wasn't high enough priority, as kapt is still necessary for projects using Hilt anyway.

I'll try to spend some time on this issue as soon as I get a bit less busy elsewhere.

**Comment by sczerwinski** [comment]
v1.4.0 has been released.
