### ISSUE TITLE
Primary naming

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [sczerwinski/android-hilt#8]
Will it use primary when it is released?

IMO it is a generic name which can lead to confusion (I don't know it is a standard in another frameworks). Is it planned to add a `secondary`?

I think something like `Injectable(...)` is more descriptive.

**Comment by sczerwinski** [comment]
It comes from [`@Primary`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Primary.html) annotation from Spring Framework.

However the naming conventions are not aligned between Dagger/Hilt and Spring (e.g. `Component` means something completely different). So `@Primary` might be confusing to developers used to Dagger/Hilt.

I think the name should refer to [`@Binds`](https://dagger.dev/api/latest/dagger/Binds.html) annotation in some way, e.g.:
- `@Bound`
- `@BoundTo`
- `@BindTo`

**Comment by JavierSegoviaCordoba** [comment]
Anvil from Square is using `@ContributesBinding` it can be a candidate too

**Comment by sczerwinski** [comment]
I decided to go with `@BoundTo`.
- it's understandable to Dagger and Hilt users,
- it's grammatically correct,
- it's not too long,
- it's different than other annotations in Dagger/Hilt/Anvil.

**Comment by JavierSegoviaCordoba** [comment]
I like it, but that `to` can be strange when you add support to detect the current supertype and if the components is not indicated no?

**Comment by sczerwinski** [comment]
There is a small obstacle with autodetecting supertype.

The annotation is:
```kotlin
annotation class BoundTo(
    val supertype: KClass<*>,
    val component: KClass<*>
)
```

I can provide a default type, but not `null`:
```kotlin
annotation class BoundTo(
    val supertype: KClass<*>? = null, // <-- this is not possible (nullable is forbidden)
    val component: KClass<*> = SingletonComponent::class // <-- this is fine
)
```

So I can either set the supertype to some general type (like `Nothing` or `Any`), which seems a bit dodgy, or I can implement another annotation:
```kotlin
annotation class Bound(
    val component: KClass<*> = SingletonComponent::class
)
```

**Comment by JavierSegoviaCordoba** [comment]
Do you think when both annotations exists, the one which doesn't infer the supertype will be used? If yes, then having two different annotations fit with that naming very well

**Comment by sczerwinski** [comment]
Yes, although rarely, for classes with 2 or more direct supertypes.
